name: ecommerce_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_rating_bar: ^4.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  google_sign_in: ^7.2.0
  http: ^1.5.0
  iconsax_flutter: ^1.0.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  logger: ^2.6.1
  lottie: ^3.3.2
  readmore: ^3.0.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1
  supabase_flutter: ^2.10.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/images/email_verify/
    - assets/icons/category/
    - assets/images/products/
    - assets/images/banners/
    - assets/images/user/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
